plugins {
    id 'groovy'
	id 'java'
	id 'war'
    id 'org.springframework.boot' version '2.7.18'
    id 'io.spring.dependency-management' version '1.0.15.RELEASE'
    id "com.github.node-gradle.node" version "7.0.2"
}

group = 'gov.nysed'
version = '1.0.0'
sourceCompatibility = '1.8'
targetCompatibility = '1.8'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.codehaus.groovy:groovy'
    runtimeOnly 'com.h2database:h2'
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

node {
    download = true
    version = '20.19.0'
    workDir = file("${project.projectDir}/.gradle/nodejs")
    nodeProjectDir = file("${project.projectDir}/frontend")
}

tasks.register('buildVue', NpmTask) {
    dependsOn npmInstall // Ensure node_modules exists first
    args = ['run', 'build']
}

tasks.register('copyVueToSpring', Copy) {
    dependsOn buildVue
    from "frontend/dist"
    into "src/main/resources/static"
}

tasks.register('writeVersionFile') {
    outputs.file('frontend/.env')
    doLast {
        project.file('frontend/.env') << "VITE_APP_VERSION=${project.version}\nVITE_basecontext_dockertutorial=dockertutorial\n"
    }
}

// Standard hook to include these in the main build lifecycle
processResources.dependsOn writeVersionFile
processResources.dependsOn copyVueToSpring