spring.application.name=docker-tutorial
# Automatically create/update tables based on Entity classes
spring.jpa.hibernate.ddl-auto=update

# Force H2 to save to a file instead of memory
spring.datasource.url=jdbc:h2:file:/data/docker_tutorial_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Create the database if it doesn't exist
spring.sql.init.mode=always
spring.h2.console.enabled=true
